<?php 
    return [

        'GET' => [
            '/' => 'ViewController@home',
            '/login' => 'ViewController@showLoginForm',
            '/register' => 'ViewController@showRegisterForm',
            '/profile'=> 'AuthController@profile',
            '/events' => 'eventController@index',
            '/logout' => 'AuthController@logout',
            '/adDash' => 'AdminController@dashboard',
            '/adAna' => 'AdminController@analytics',
            '/adRep' => 'AdminController@reports',
            '/adSet' => 'AdminController@settings',
            '/parDash' => 'ParticipantController@dashboard',
            '/explore' => 'ViewController@explore',
            '/myEvents' => 'ParticipantController@events',
            '/parProf' => 'ParticipantController@profile',
            '/orgDash' => 'OrganizerController@dashboard',
            '/orgAna' => 'OrganizerController@analytics',
            '/orgSpon' => 'OrganizerController@sponsors',
            '/orgProf' => 'OrganizerController@profile',
            '/createEvent' => 'OrganizerController@createEvent',
            '/editEvent/{id}' => 'OrganizerController@editEvent',
            '/sponDash' => 'SponsorController@dashboard',
            '/sponAna' => 'SponsorController@analytics',
            '/sponProf' => 'SponsorController@profile',
            '/sponEditProf' => 'SponsorController@editProfile',
            '/sponPortfolio' => 'SponsorController@viewPortfolio',
            '/sponPortfolioItem/{id}' => 'SponsorController@viewPortfolioItem',
            '/sponAddPortfolio' => 'SponsorController@addPortfolio',
            '/sponEditPortfolio' => 'SponsorController@editPortfolio',
            '/sponFundEvent' => 'SponsorController@fundEvent',
            '/sponMySponsorships' => 'SponsorController@mySponsorships',
            '/sponSponsor' => 'SponsorController@viewSponsorship',
            '/sponRequests' => 'SponsorController@viewRequests',
            '/sponRequest' => 'SponsorController@viewRequest',
            '/sponPromotions' => 'SponsorController@viewPromotions',
            '/sponCreatePromotion' => 'SponsorController@createPromotionForm',
            '/sponEditPromotion' => 'SponsorController@editPromotionForm',
            '/suppDash' => 'SupplierController@dashboard',
            '/suppProf' => 'SupplierController@profile',
            '/suppAna' => 'SupplierController@analytics',
            '/addProduct' => 'SupplierController@addProduct',
            '/editProduct/{id}' => 'SupplierController@editProduct',
        ],

        'POST' => [
            '/logindata' => 'AuthController@login',
            '/registerdata' => 'AuthController@register',
            '/profile/update' => 'AuthController@updateProfile',
            '/organizer/update' => 'OrganizerController@updateProfile',
            '/participant/update' => 'ParticipantController@updateProfile',
            '/sponsor/update' => 'SponsorController@updateProfile',
            '/sponsor/save' => 'SponsorController@saveProfile',
            '/sponsor/delete' => 'SponsorController@deleteProfile',
            '/supplier/update' => 'SupplierController@updateProfile',
            '/sponsor/createPortfolio' => 'SponsorController@createPortfolio',
            '/sponsor/updatePortfolio' => 'SponsorController@updatePortfolio',
            '/sponsor/deletePortfolio' => 'SponsorController@deletePortfolio',
            '/sponsor/sendRequest' => 'SponsorController@sendRequest',
            '/sponsor/updateFunding' => 'SponsorController@updateFunding',
            '/sponsor/updateRequestStatus' => 'SponsorController@updateRequestStatus',
            '/sponsor/addRequestNotes' => 'SponsorController@addRequestNotes',
            '/sponsor/createPromotion' => 'SponsorController@createPromotion',
            '/sponsor/updatePromotion' => 'SponsorController@updatePromotion',
            '/sponsor/deletePromotion' => 'SponsorController@deletePromotion',
            '/organizer/createEvent' => 'EventController@createEvent',
            '/organizer/editEvent' => 'EventController@editEvent',
            '/organizer/deleteEvent' => 'EventController@deleteEvent',
            '/supplier/createProduct' => 'SupplierController@createProduct',
            '/supplier/updateProduct' => 'SupplierController@updateProduct',
            '/supplier/deleteProduct' => 'SupplierController@deleteProduct',
            '/viewEvent' => 'ViewController@viewEvent',
        ]
    ]
?>